### ISSUE TITLE
0 Mana Charge Speed and Slime Buff

### ISSUE THREAD

**Issue by TsumiHokiro** [TheHorscht/Anvil-of-Destiny#1]
I've noticed that if you try to use the Slime buff on the anvil with a 0 Mana Charge Speed on the anvil the Anvil will consume both the potion and the wand and not return anything; worse, it will sit waiting with the lights on, accepting more input.
Ps: I managed to get it to 0 by using the Vomit Buff, btw.

**Comment by TsumiHokiro** [comment]
Just posting a solution I came up with
--Slime Potion #110
wand.manaChargeSpeed = math.max(1, wand.manaChargeSpeed - math.ceil(math.abs(wand.manaChargeSpeed) * Randomf(0.05, 0.10)))

In case you'd like to do the same for the vomit...
--Vomit Potion #360
wand.manaChargeSpeed = math.max(1, wand.manaChargeSpeed * Randomf(0.4, 0.6))

I won't push a request since this repo does not seem to be in sync with steam seeing that it was last updated long long ago anyway...

**Comment by TheHorscht** [comment]
Thanks for letting me know, fixed in the new update I just pushed.

**Comment by TsumiHokiro** [comment]
Alright, thanks for the fix, closing the issue as well since it's been left open.
