### ISSUE TITLE
Anvil stuck after adding potions

### ISSUE THREAD

**Issue by Mg138** [TheHorscht/Anvil-of-Destiny#3]
![image](https://user-images.githubusercontent.com/33348966/129438979-2dc0060d-5caf-4c2e-8207-49ad85e62343.png)
This has happened more than once, and the wand is stuck inside. Reloading the world doesn't make a difference.
logger.txt doesn't say anything about it.

Using 1.15.4(latest)

**Comment by Mg138** [comment]
The log does output something
```
Noita (Apr 23 2021) - 20210814-154217
-------------------------------------------
Lua error: [string "mods/anvil_of_destiny/init.lua"]:21: attempt to index field 'spawn_level' (a nil value)
Lua error: [string "mods/anvil_of_destiny/files/entities/anvil/an..."]:121: Argument 'which' is invalid. Given: emitter3
Lua error: [string "mods/anvil_of_destiny/files/entities/anvil/an..."]:121: Argument 'which' is invalid. Given: emitter3
Lua error: 
```

**Comment by TheHorscht** [comment]
What other mods are you using that add custom spells?

**Comment by Mg138** [comment]
The My Little Pony mod, though custom spells from it merge and emerge just fine.

**Comment by TheHorscht** [comment]
I just pushed an update for the Steam version, it should be fixed now. The pony mod adds a spell without `spawn_level` defined, I never added a safety check for that. Thanks for letting me know.

**Comment by Mg138** [comment]
I'll close the issue if the problem disappears. Hope it will!
