### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by Tilation** [TheHorscht/Anvil-of-Destiny#5]
The page https://github.com/TheHorscht/Anvil-of-Destiny/wiki/Recipe-effects is outdated. Would be nice to update it.

**Comment by TheHorscht** [comment]
What about it is outdated? Can you give some examples?

**Comment by XM666-Dev** [comment]
![shot_20240802-131859-1213710200--387-8482-00829163](https://github.com/user-attachments/assets/6c9eb93f-fba8-4186-9c3c-33f03b6327b0)
This potion from [More Stuff](https://steamcommunity.com/sharedfiles/filedetails/?id=2910427839) isn't in wiki
Is this recipe added by More Stuff?

**Comment by TheHorscht** [comment]
Looks like the recipe is being added by Apotheosis. I'm not gonna put 3rd party recipes on the wiki because it's too much work to keep track of them. In my opinion they should be explained by the mod which adds the materials and recipes for them.
