### ISSUE TITLE
Always cast changed on wand combining

### ISSUE THREAD

**Issue by duno9** [TheHorscht/Anvil-of-Destiny#8]
Not sure if this is a bug or intended, but when one wand has an always cast and another does not, and you combine them, the always cast is either removed or changed. I can understand that having one always cast and one not should result in a wand that might or might not have an always cast, but I feel like if it does have that always cast, it should be the same one the original wand had.

**Comment by TheHorscht** [comment]
Yes that's working as intended. I thought it might be useful because lots of wands have bad always casts and this way you have a chance (or guaranteed if both wands have an always cast) to reroll it.

**Comment by duno9** [comment]
That makes sense, thanks for the quick response! Maybe something to think about adding as a setting.
